# Generated by Django 5.2.6 on 2025-10-20 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('risk', 'risk'), ('reminder', 'reminder')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringPaymentReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('vivienda', 'vivienda'), ('servicios_basicos', 'servicios_basicos'), ('alimentacion', 'alimentacion'), ('transporte', 'transporte'), ('salud', 'salud'), ('entretenimiento', 'entretenimiento'), ('streaming_suscripciones', 'streaming_suscripciones'), ('mascotas', 'mascotas'), ('cuidado_personal', 'cuidado_personal'), ('deudas_prestamos', 'deudas_prestamos'), ('ahorro_inversion', 'ahorro_inversion'), ('seguros', 'seguros'), ('educacion_desarrollo', 'educacion_desarrollo'), ('regalos_celebraciones', 'regalos_celebraciones'), ('viajes_vacaciones', 'viajes_vacaciones'), ('imprevistos', 'imprevistos')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurrence_type', models.CharField(default='monthly', max_length=20)),
                ('payment_day', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
