# Generated by Django 5.2.6 on 2025-10-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_alert_type_recurringpaymentreminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringpaymentreminder',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelTable(
            name='recurringpaymentreminder',
            table='recurring_payments_reminder',
        ),
    ]
