# Generated by Django 5.2.6 on 2025-10-30 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('vivienda', 'vivienda'), ('servicios_basicos', 'servicios_basicos'), ('alimentacion', 'alimentacion'), ('transporte', 'transporte'), ('salud', 'salud'), ('entretenimiento', 'entretenimiento'), ('streaming_suscripciones', 'streaming_suscripciones'), ('mascotas', 'mascotas'), ('cuidado_personal', 'cuidado_personal'), ('deudas_prestamos', 'deudas_prestamos'), ('ahorro_inversion', 'ahorro_inversion'), ('seguros', 'seguros'), ('educacion_desarrollo', 'educacion_desarrollo'), ('regalos_celebraciones', 'regalos_celebraciones'), ('viajes_vacaciones', 'viajes_vacaciones'), ('imprevistos', 'imprevistos')], max_length=50)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incomes',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
