# Generated by Django 5.2.6 on 2025-09-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('gastos_esenciales', 'gastos_esenciales'), ('gastos_personales', 'gastos_personales'), ('financieros', 'financieros'), ('educacion', 'educacion'), ('otros', 'otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
