# Generated by Django 5.2.6 on 2025-10-01 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_alter_expense_category_alter_expense_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('vivienda', 'vivienda'), ('servicios_basicos', 'servicios_basicos'), ('alimentacion', 'alimentacion'), ('transporte', 'transporte'), ('salud', 'salud'), ('entretenimiento', 'entretenimiento'), ('streaming_suscripciones', 'streaming_suscripciones'), ('mascotas', 'mascotas'), ('cuidado_personal', 'cuidado_personal'), ('deudas_prestamos', 'deudas_prestamos'), ('ahorro_inversion', 'ahorro_inversion'), ('seguros', 'seguros'), ('educacion_desarrollo', 'educacion_desarrollo'), ('regalos_celebraciones', 'regalos_celebraciones'), ('viajes_vacaciones', 'viajes_vacaciones'), ('imprevistos', 'imprevistos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
    ]
