# Generated by Django 5.2.6 on 2025-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_expense_created_at_income_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
