# Generated by Django 5.2.6 on 2025-09-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='balances',
        ),
    ]
